# ---------------------- AURABLOCKS ----------------------

# loc: WorldName X Z Y Radius Yaw(P/Abs) Pitch(P/Abs)
# dest: portal/location/player

aurablock:

  test1:
    active: all
    loc: Adventure 276.5 -2197.5 69 2
    auras:
      - treeClimb
      - autofeedheal

  test2:
    active: all
    loc: Adventure 271.5 -2197.5 69 2
    auras:
      - treeClimb
      - ugh-lite
