# ---------------------- WORKORDERS ----------------------

# 

workorder:

  cob1:
    name: "&6Cobble &efor new wall"
    descr: "&cRedwind Keep &7needs &3Cobble"
    active: all
    icon: COBBLESTONE
    coolId: wo-cob1
    coolTime: 16h
    reward: $3,750
    reqMat:
      - 1280 COBBLESTONE
    reqDescr:
      - "&6Cobble &efor new wall"
      - "&a$3,750"
      - "&f16h &7between orders"
      - "&620 stacks &7of &3Cobble"

  gran1:
    name: "&6Polished Granite &efor a statue"
    descr: "&cRedwind Keep &7needs &3Polished Granite"
    active: all
    icon: STONE:2
    coolId: wo-gran1
    coolTime: 20h
    reward: $5,500
    reqMat:
      - 640 STONE:2
    reqDescr:
      - "&6Polished Granite &efor a statue"
      - "&a$5,500"
      - "&f20h &7between orders"
      - "&610 stacks &7of &3Polished Granite"

  sb1:
    name: "&6Stone Brick &efor a well"
    descr: "&cAdventure City &7needs &3Stone Brick"
    active: all
    icon: SMOOTH_BRICK
    coolId: wo-sb1
    coolTime: 12h
    reward: $5,500
    reqMat:
      - 448 SMOOTH_BRICK
    reqDescr:
      - "&6Stone Brick &efor a well"
      - "&a$3,100"
      - "&f12h &7between orders"
      - "&67 stacks &7of &3Stone Brick"

  oak1:
    name: "&6Wood &efor new tower"
    descr: "&2Raylen &7needs &3Oak Logs"
    active: all
    icon: LOG:0
    coolId: wo-oak1
    coolTime: 24h
    reward: $3,500
    reqMat:
      - 512 LOG:0
    reqDescr:
      - "&6Wood &efor new tower"
      - "&a$3,500"
      - "&f24h &7between orders"
      - "&68 stacks &7of &3Oak Logs"

  spruce1:
    name: "&6Wood &efor warehouse expansion"
    descr: "&2Raylen &7needs &3Spruce Logs"
    active: all
    icon: LOG:1
    coolId: wo-spruce1
    coolTime: 22h
    reward: $3,000
    reqMat:
      - 320 LOG:1
    reqDescr:
      - "&6Wood &efor warehouse expansion"
      - "&a$3,000"
      - "&f22h &7between orders"
      - "&65 stacks &7of &3Spruce Logs"

  flowers1:
    name: "&6Flowers &efor Riverwalk"
    descr: "&2Raylen &7needs &3Flowers"
    active: all
    icon: YELLOW_FLOWER
    coolId: wo-flowers1
    coolTime: 22h
    reward: $550
    reqMat:
      - 64 YELLOW_FLOWER
      - 64 RED_ROSE
    reqDescr:
      - "&6Flowers &efor Riverwalk"
      - "&a$550"
      - "&f22h &7between orders"
      - "&61 stack &7of &3Dandelion Flowers"
      - "&61 stack &7of &3Poppy Flowers"

  bow1:
    name: "&6Army Supplies &efor Defense"
    descr: "&9The Castle &7needs &3Archer Gear"
    active: all
    icon: STRING
    coolId: wo-bow1
    coolTime: 22h
    reward: $1,800
    reqMat:
      - 64 STRING
      - 128 STICK
      - 64 FLINT
      - 64 FEATHER
    reqDescr:
      - "&6Army Supplies &efor Defense"
      - "&a$1,800"
      - "&f22h &7between orders"
      - "&61 stack &7of &3String"
      - "&62 stacks &7of &3Sticks"
      - "&61 stack &7of &3Flint"
      - "&61 stack &7of &3Feathers"

  goldi1:
    name: "&6Gold &efor the treasury"
    descr: "&bThe Treasury &7needs &3Gold Ingots"
    active: all
    icon: GOLD_INGOT
    coolId: wo-goldi1
    coolTime: 14h 30m
    reward: $5,000
    reqMat:
      - 64 GOLD_INGOT
    reqDescr:
      - "&6Gold &efor the treasury"
      - "&a$5,000"
      - "&f14h 30m &7between orders"
      - "&61 stack &7of &3Gold Ingots"

  flesh1:
    name: "&6Zombie Parts &efor experiments"
    descr: "&bApothacaries &7need &3Rotten Flesh"
    active: all
    icon: ROTTEN_FLESH
    coolId: wo-flesh1
    coolTime: 22h
    reward: $3,000
    reqMat:
      - 640 ROTTEN_FLESH
    reqDescr:
      - "&6Zombie Parts &efor experiments"
      - "&a$3,000"
      - "&f22h &7between orders"
      - "&610 stacks &7of &3Rotten Flesh"

  dio1:
    name: "&6Diorite &efor city walls"
    descr: "&bElf Kingdom &7needs &3Diorite"
    active: all
    icon: STONE:3
    coolId: wo-dio1
    coolTime: 16h
    reward: $4,100
    reqMat:
      - 960 STONE:3
    reqDescr:
      - "&6Diorite &efor city walls"
      - "&a$4,100"
      - "&f16h &7between orders"
      - "&615 stacks &7of &3Diorite"

  ironblock1:
    name: "&6Iron Blocks &efor jail cells"
    descr: "&bPrison Island &7needs &3Iron Blocks"
    active: all
    icon: IRON_BLOCK
    coolId: wo-ironblock1
    coolTime: 22h
    reward: $7,000
    reqMat:
      - 32 IRON_BLOCK
    reqDescr:
      - "&6Iron Blocks &efor jail cells"
      - "&a$7,000"
      - "&f22h &7between orders"
      - "&61/2 stack &7of &3Iron Blocks"
      
  coal1:
    name: "&6Coal Blocks &efor smelters"
    descr: "&bDwarfs &7need &3Coal Blocks"
    active: all
    icon: COAL_BLOCK
    coolId: wo-coal1
    coolTime: 22h
    reward: $13,800
    reqMat:
      - 256 COAL_BLOCK
    reqDescr:
      - "&6Coal Blocks &efor smelters"
      - "&a$13,800"
      - "&f22h &7between orders"
      - "&64 stacks &7of &3Coal Blocks"

  fish1:
    name: "&6Fish &efor public market"
    descr: "&eneek'lii &7needs &3Fish"
    active: all
    icon: RAW_FISH
    coolId: wo-fish1
    coolTime: 20h
    reward: $3,600
    reqMat:
      - 64 RAW_FISH
      - 32 RAW_FISH:1
    reqDescr:
      - "&6Fish &efor public market"
      - "&a$3,600"
      - "&f20h &7between orders"
      - "&61 stack &7of &3Raw Fish"
      - "&61/2 stack &7of &3Raw Salmon"
      
  fish2:
    name: "&6Rare fish &efor sushi hut"
    descr: "&bneek'lii sushi hut &7needs &3fish"
    active: all
    icon: RAW_FISH:2
    coolId: wo-fish2
    coolTime: 1d 8h
    reward: $6,600
    reqMat:
      - 32 RAW_FISH:1
      - 16 RAW_FISH:2
      - 16 RAW_FISH:3
    reqDescr:
      - "&6Rare fish &efor sushi hut"
      - "&a$6,600"
      - "&f1d 8h &7between orders"
      - "&61/2 stack &7of &3Raw Salmon"
      - "&61/4 stack &7of &3Pufferfish"
      - "&61/4 stack &7of &3Clownfish"
      