#default config.yml

testmsg: All hail

# ---------------------- ALL ----------------------

vanilla:
  - hearts 20
  - className Plebian

# ---------------------- CLERGY ----------------------

aura_heal:
  - self true
  - className Heal
  - heal 2 5

aura_autofeed:
  - self true
  - className AutoFeed
  - autofeed 1 1

aura_autoheal:
  - self true
  - className AutoHeal
  - autoheal 1 1

aura_autofeedheal:
  - self true
  - className AutoFeedHeal
  - autoheal 1 1
  - autofeed 1 1

aura_mine:
  - self true
  - className Mine
  - haste 2 30

aura_regen:
  - self true
  - className Regen
  - regen 2 15

aura_rabbit:
  - self false
  - className Rabbit
  - speed 3 5
  - jump 2 17
  
aura_super_rabbit:
  - self true
  - className SuperRabbit
  - speed 2 10
  - jump 4 12

aura_ugh:
  - self false
  - className Ugh
  - sloth 1 10
  - disorientation 2 12


# ---------------------- SOLDIER ----------------------

sol_bowman:
  - hearts 21
  - className Bowman
  
sol_warrior:
  - hearts 23
  - className Warrior

sol_knight:
  - hearts 25
  - className Knight

sol_captain:
  - hearts 27
  - className Captain 

sol_kingsguard:
  - hearts 29
  - className Kingsguard

sol_commander:
  - hearts 30
  - className Commander 

sol_hero:
  - hearts 34
  - className Hero

# ---------------------- DUNGEONS ----------------------

dungeon_lavadome:
  - no feed
  - no heal

dungeon_flaskd:
  - no heal

# ---------------------- ITEMS ----------------------

# ---------------------- PORTALS ----------------------

# loc: WorldName X Z Y Radius Yaw(P/Abs) Pitch(P/Abs)
# dest: portal/location/player

portal:

  hosSuhnOahr:
    active: none
    message: none
    outbound: Adventure 595 -2045 123 1
    dest: portal.placeSundialSuhnOahr.inbound
   
  testSuhnOahr:
    active: all
    message: none
    outbound: Adventure 285 -2197 67 1
    dest: portal.placeSundialSuhnOahr.inbound

  testSuhnOahr3:
    active: all
    message: none
    outbound: Adventure 290 -2197 67 1
    dest2: Adventure -4823.5 -314.5 79 0 P P
    destmessage: "&cHere we go!!"
    dest: portal.townSuhnOahr.inbound

  testSuhnOahr2:
    active: all
    message: none
    outbound: Adventure 281 -2197 67 1
    dest: portal.swordSuhnOahr.inbound

  placeSundialSuhnOahr:
    active: inbound
    inbound: Adventure 161 -2224 81 0 229.05 1.2
    inboundmessage: "&6You find yourself standing atop an ancient &echronometer"

  swordSuhnOahr:
    active: none
    inbound: Adventure 206 -2245 68 0 254.583 -20.7

  townSuhnOahr:
    active: none
    inbound: Adventure 129 -2170 65 0 P P
    inbound2: Adventure 129 -2170 65 0 321.75 -22.8
    inboundmessage: "&2A modern &aelvish &2dock is alive with activity"

  jdMaintenance:
    active: all
    message: none
    outbound: Adventure -1141 -2390 3 1
    dest: portal.jdPillarIn.inbound

  jdPillarOut:
    active: all
    message: none
    outbound: Adventure -1141 -2398 7 1
    dest: portal.jdChair.inbound

  jdPillarIn:
    active: none
    inbound: Adventure -1141 -2402 7 0 P P
    inboundmessage: "&4Welcome to the dwarf forge maintenance area. Careful, contents may be &chot."
   
  jdChair:
    active: none
    inbound: Adventure -1156 -2374 16 0 P P
    inboundmessage: "&4Watch your step!"

  glendaleTree:
    active: all
    outbound: Adventure -2468.5 761.5 61 1
    inbound: Adventure -2468 761 61 0 P P
    dest: portal.treeDungF4i.inbound

  glendaleGraveyard:
    active: all
    outbound: Adventure -2402 875 66 1
    dest: portal.treeDungF4i.inbound

  quiOne:
    active: none
    inbound: Adventure -179 812 66 0 -89 1
    inboundmessage: "&2After falling through the tree, you find yourself in a small cave"

  treeDungF4i:
    active: none
    inbound: world -1629.5 -2228.5 79 0 P P
    inbound2: Adventure -4823 -314 79 0 P P
    inboundmessage: "&4Ouch Lava!!! &9Ohhhh water!!"


# ---------------------- ANNOUCE ----------------------

announcement:
    # Use this flag to temporary disable the announcements.
    # enabled: false, means that there wouldn't be any announcements.
    enabled: true

    # Set this to true will announce in random order.
    # 'false' will announce in sequential (one after another) order.
    random: true

    # Defines the prefix for the announcement. Use & + hex char for color codes.
    prefix: ""

    # The time of one interval in seconds.
    interval: 299

    # List of messages to announce. You could use color codes by using & + hex chars too.
    messages:
    - '&5&l>>> &5&l[&6&lInfo&5&l] &6We have a Teamspeak! Join the conversation! TS-IP: &7legendsandkings.typefrag.com &5&l<<<'
    - '&5&l>>> &5&l[&6&lInfo&5&l] &e/Warp Info &6for all the tips, tricks, and knowledge about &5Legends & Kings &6! &5&l<<<'
    - '&5&l>>> &5&l[&6&lInfo&5&l] &e/Warp Adventure &6To Start Your Adventure Today! &5&l<<<'
    - '&5&l>>> &5&l[&6&lInfo&5&l] &6Visit &elegendsandkings.net &6for everything that doesnt fit on a sign! &5&l<<<'
    #- '&5&l>>> &5&l[&6&lInfo&5&l] &6Message &5&l<<<'
    - '&b&l>>> &b&l&o[&6&l&oTips&b&l&o] &6Search &eminecraft.gamepedia.com &6for information on everything minecraft. All the details included!&b&l<<<'
    - '&b&l>>> &b&l&o[&6&l&oTips&b&l&o] &6Looking for just the right block for your build? &eminecraft-ids.grahamedgecombe.com &b&l<<<'
    - '&b&l>>> &b&l&o[&6&l&oTips&b&l&o] &6Check out &ewww.minecraftcrafting.info &6for all your crafting recipes! &b&l<<<'
    - '&b&l>>> &b&l&o[&6&l&oTips&b&l&o] &6Learn about all your skills on the McMMO wiki! &ehttp://mcmmo.wikia.com/wiki/McMMO_Wiki &b&l<<<'
    - '&5&l>>> &5&l[&6&lRules&5&l] &6Do &e/rules&6, &e/rules 2 &6& &e/rules 3 &6and read ze rules! &5&l<<<'
    - '&5&l>>> &5&l[&6&lReport It&5&l] &6Use &e/report &6to report grief(seek online staff first please), bugs, exploits, etc. please do NOT abuse. &5&l<<<'
    - '&5&l>>> &5&l[&6&lWanted&5&l] &6We`re looking for potential staff personel, if you think you have what it takes, apply on the forums! &5&l<<<'
    #- '&5&l>>> &5&l[&6&lSALE!&5&l] &6Shop today at &e/warp Shops &6and buy or sell your items! (contact an admin to purchase a shop) &5&l<<<'

    # Use to enable or disable the motd.
    motdEnabled: false

    # Use to define the motd.
    motd: "Test announcement."

    # Use to enable or disable the MOTD prefix.
    motd-show-prefix: true


