# ---------------------- GUILDS ----------------------

# loc: WorldName X Z Y Radius Yaw(P/Abs) Pitch(P/Abs)

guild:

  0:
    name: QuickTest
    color: a
    houseLoc: world 0 70 0 90 5
    members: []
    invites: []
    requests: []
